### ISSUE TITLE
Feature to view Used Gears and Game Settings of Players

### ISSUE THREAD

**Issue by Rinrin0413** [Sarf-Esports/website#123]
## 概要

当チーム公式 X アカウントにてポストされている「[選手の使用デバイス&ゲーム設定紹介](https://x.com/search?q=from%3Arevati_jp%20%E9%81%B8%E6%89%8B%E3%81%AE%E4%BD%BF%E7%94%A8%E3%83%87%E3%83%90%E3%82%A4%E3%82%B9%26%E3%82%B2%E3%83%BC%E3%83%A0%E8%A8%AD%E5%AE%9A%E7%B4%B9%E4%BB%8B&f=live)」の内容をサイト内で確認できる機能を実装する。

## 仕様

- [x] 各メンバーカードのソーシャルアカウントの最後尾にボタンを設置する
    - [x] ボタンにはゲームコントローラーのアイコンを使う
    - [x] 右寄せ
- [x] ボタン押下時でモーダルを表示 ~~挙動は検討中だが、リンクではなくサイト内で完結させる~~
    - ~~検討中の挙動:~~
        - ~~要素が全画面に広がってくるようにする~~
        - ~~別ページを用意~~
- [x] レイアウト (検討中) :
    - ~~上部には、ポストに添付されている画像を配置~~ 頻繁な変更を考慮して却下。
    - [x] 上記の画像の代わりにキャラクターを配置 ~~(詳細は検討中)~~
    - [x] その下に表形式で詳細を並べる
    - [x] クロスヘア設定は、添付されている画像内の言語バラバラなため、上記のように表形式に

## ToDo

- [x] この項目を新しいファイルに移動する。
- [x] 追加したフィールドの説明を `MEMBERS.ts` 又は上記の新しいファイルの冒頭のドキュメントに記載する。
- [x] 適切な翻訳を用意する。(一部 GPT での翻訳で妥協)
