### ISSUE TITLE
Support environments where JS is disabled

### ISSUE THREAD

**Issue by Rinrin0413** [Sarf-Esports/website#166]
Support the environments where JavaScript is disabled.

## ToDo

- [x] Add a `<noscript>` tag.
- [x] Fix some elements that remain hidden. (causes by `RevealFadeIn` component)
- [x] Fix some unusable features.
