### ISSUE TITLE
Improve directory structure for article files

### ISSUE THREAD

**Issue by Rinrin0413** [Sarf-Esports/website#171]
Currently, all the article Markdown files are being directly placed in the `articles` directory.  As the number of articles increases, this flat structure makes it hard to manage the files.
So change the structure from `articles/YYYYMMDD*.md` to `articles/YYYY/MM/YYYYMMDD*.md`.

## ToDo

- [x] Change the structure.
- [x] Update the npm script `create-article`.
- [x] Update the documentation for the article files.
